#!/usr/bin/env bash

set -eu

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export PATH=$here/compiler/i686-elf/bin:$here/lib/objconv:$PATH
export CC=i686-elf-gcc
export CXX=i686-elf-g++
export CPP=i686-elf-cpp
export LD=i686-elf-gcc
export AS=i686-elf-as

bash
