#!/usr/bin/env bash

set -eu

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

target=i386-elf
gcc_version=5.3.0
host=Linux-x86_64
cross=$HOME/cross
compiler=$target-$gcc_version-$host
compiler_archive=$compiler.tar.xz

if [ ! -d "$cross/$compiler" ];
then
  echo "Installing cross-compiler"
  mkdir -p ~/cross
  pushd ~/cross
    wget "http://newos.org/toolchains/$compiler_archive"
    tar xvf $compiler_archive
  popd
else
  echo "Cross-compiler already installed"
fi

export PATH=$cross/$compiler/bin:$PATH
export CC=$target-gcc
export CXX=$target-g++
export CPP=$target-cpp
export LD=$target-gcc
export AS=$target-as

bash
